services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: procyon_web
    # SIGTERM works with python app.py
    # SIGINT if you want to use flask run
    stop_signal: SIGTERM
    ports:
      - '5000:5000'
    volumes:
      - ./models:/app/models
    restart: unless-stopped